### ISSUE TITLE
For headings that contain links, preserve the link in favor of the clickable heading

### ISSUE THREAD

**Issue by caphesuagey** [coldrye-confluence/clickable-anchors-plugin#6] opened 2021-08-23 10:38 UTC
If a document heading contains a link to another page, the link cannot be opened, because the plugin still treats this heading as an anchor. The only way to open the linked page is right-click > Open from the context menu. Is there a way to change this behavior so that clicking a heading that contains a link would open the linked page?

**Comment by silkentrance** [comment] 2021-08-31 14:22
This is a duplicate of #2.

**Closed as completed** 2021-11-12 20:30 UTC
Labels: bug
